#!/usr/bin/env python3
"""One connection helper, so every module opens the database the same way and
the schema is applied exactly once per process rather than on every connect.

    from db import connect, session, now

    python3 db.py --maintain          # checkpoint the WAL, VACUUM if a migration asked for it
    python3 db.py --rebuild-derived   # drop+recreate derived tables whose CHECK widened
"""
from __future__ import annotations

import sqlite3
import sys
import time
from contextlib import contextmanager
from pathlib import Path

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))
import person                               # noqa: E402
DB = person.path(HERE / "jobscout.db", "jobscout.db")
SCHEMA = HERE / "schema.sql"

# Bump when a one-off data migration is added to `_ONE_OFFS`. Stored in the
# database's `user_version` pragma, so each migration runs exactly once per
# file, however many processes open it.
SCHEMA_VERSION = 1


def now() -> int:
    """Epoch seconds. One definition, so timestamps across tables compare."""
    return int(time.time())


# Columns added to tables that already exist in the wild. `CREATE TABLE IF NOT
# EXISTS` cannot add a column, and dropping a live table to widen it would take
# the application history with it -- which is the one thing here that cannot be
# rebuilt from a re-run.
MIGRATIONS = [
    ("application", "outcome", "TEXT"),
    ("application", "outcome_at", "INTEGER"),
    ("application", "note", "TEXT"),
]


# Tables whose CHECK constraint has widened. SQLite cannot alter a constraint,
# and these tables hold **derived** data -- every row is regenerated by its own
# stage on the next `--all` run -- so dropping and letting schema.sql recreate
# them costs a re-run, not information. Never put a table here that holds
# anything a re-run could not reproduce.
#
# Applied only by `python3 db.py --rebuild-derived`, never on connect: a DROP
# TABLE that can fire from inside any process that opens the database -- the
# board answering an HTTP request, a test -- is a footgun, not a migration.
REBUILD_IF_MISSING = [
    ("geo", "'company'"),
]


def _v1(conn: sqlite3.Connection) -> None:
    """job.description was a byte-for-byte copy of the richest
    posting.description -- roughly 200 MB of the file. The `job_text` view now
    serves it from the posting table; the column stays (NULL) so old readers
    do not break. Also: salary_unparsed had no key and `--all` re-inserted the
    same ~2,000 rows on every pass."""
    conn.execute("UPDATE job SET description = NULL WHERE description IS NOT NULL")
    conn.execute(
        "DELETE FROM salary_unparsed WHERE id NOT IN "
        "(SELECT MIN(id) FROM salary_unparsed GROUP BY job_id, raw)")
    conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_salary_unparsed "
                 "ON salary_unparsed(job_id, raw)")
    conn.execute("INSERT OR REPLACE INTO meta (key, value) VALUES ('needs_vacuum', '1')")


_ONE_OFFS = {1: _v1}


def migrate(conn: sqlite3.Connection) -> None:
    for table, column, decl in MIGRATIONS:
        existing = {r[1] for r in conn.execute(f"PRAGMA table_info({table})")}
        if existing and column not in existing:
            conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {decl}")
    version = conn.execute("PRAGMA user_version").fetchone()[0]
    for v in range(version + 1, SCHEMA_VERSION + 1):
        _ONE_OFFS[v](conn)
        conn.execute(f"PRAGMA user_version = {v}")
    conn.commit()


def rebuild_derived(conn: sqlite3.Connection) -> list[str]:
    rebuilt = []
    for table, marker in REBUILD_IF_MISSING:
        row = conn.execute(
            "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?",
            (table,)).fetchone()
        if row and row[0] and marker not in row[0]:
            conn.execute(f"DROP TABLE {table}")
            conn.executescript(SCHEMA.read_text())
            rebuilt.append(table)
    conn.commit()
    return rebuilt


_APPLIED: set[str] = set()


def connect(path: Path | str | None = None, *, readonly: bool = False
            ) -> sqlite3.Connection:
    """Open the database, creating and migrating it on the first open per
    process. `schema.sql` is entirely CREATE ... IF NOT EXISTS, so it is both
    the create path and the migrate path -- but 440 lines of it on every
    connection was the board re-checking 21 tables per HTTP request.

    `readonly=True` opens with `mode=ro` and applies nothing: for tests and
    inspection that must not be able to write, however the schema drifts.
    """
    target = str(Path(path or DB).resolve())
    if readonly:
        conn = sqlite3.connect(f"file:{target}?mode=ro", uri=True, timeout=30.0)
        conn.row_factory = sqlite3.Row
        return conn
    # 30 seconds rather than failing instantly on a lock.
    #
    # The board-discovery sweep runs for minutes and commits after every
    # employer; anything else touching the database in that window used to get
    # "database is locked" and die, which killed a 400-company sweep 60
    # companies in. WAL already allows concurrent readers -- this makes a
    # concurrent *writer* wait its turn instead of giving up.
    conn = sqlite3.connect(target, timeout=30.0)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    conn.execute("PRAGMA busy_timeout = 30000")
    if target not in _APPLIED:
        conn.executescript(SCHEMA.read_text())
        migrate(conn)
        _APPLIED.add(target)
    return conn


@contextmanager
def session(path: Path | str | None = None):
    """`with session() as conn:` -- commit on success, roll back on error, and
    **close** either way. `with connect() as conn:` only commits: the board
    used it for every request and leaked one handle per hit, and each leaked
    handle pinned a WAL snapshot that could never be checkpointed."""
    conn = connect(path)
    try:
        with conn:
            yield conn
    finally:
        conn.close()


def job_description(conn: sqlite3.Connection, job_id: int) -> str:
    row = conn.execute("SELECT description FROM job_text WHERE job_id = ?",
                       (job_id,)).fetchone()
    return (row["description"] if row else None) or ""


def maintain(conn: sqlite3.Connection, *, vacuum: bool | None = None) -> dict:
    """End-of-run housekeeping. The WAL is folded back into the main file, and
    the file is VACUUMed when a migration asked for it (or when forced)."""
    out: dict = {}
    conn.commit()
    busy, log, moved = conn.execute("PRAGMA wal_checkpoint(TRUNCATE)").fetchone()
    out["checkpoint"] = {"busy": busy, "wal_pages": log, "checkpointed": moved}
    flagged = conn.execute(
        "SELECT value FROM meta WHERE key = 'needs_vacuum'").fetchone()
    if vacuum or (vacuum is None and flagged and flagged[0] == "1"):
        before = Path(conn.execute("PRAGMA database_list").fetchone()[2]).stat().st_size
        conn.execute("VACUUM")
        conn.execute("DELETE FROM meta WHERE key = 'needs_vacuum'")
        conn.commit()
        after = Path(conn.execute("PRAGMA database_list").fetchone()[2]).stat().st_size
        out["vacuum"] = {"before_mb": round(before / 1e6), "after_mb": round(after / 1e6)}
        # In WAL mode a VACUUM writes the rebuilt file *into the WAL*; fold it
        # back now, or the -wal is as big as the database it just shrank.
        busy, log, moved = conn.execute("PRAGMA wal_checkpoint(TRUNCATE)").fetchone()
        out["checkpoint_after_vacuum"] = {"busy": busy, "wal_pages": log, "checkpointed": moved}
    return out


def log_stage(conn: sqlite3.Connection, stage: str, ok: bool,
              detail: str = "", started: int | None = None) -> None:
    conn.execute(
        "INSERT INTO run_log (stage, ok, detail, started_at, ended_at) "
        "VALUES (?, ?, ?, ?, ?)",
        (stage, 1 if ok else 0, detail, started or now(), now()),
    )
    conn.commit()


def main(argv: list[str]) -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--maintain", action="store_true")
    ap.add_argument("--vacuum", action="store_true", help="force a VACUUM")
    ap.add_argument("--rebuild-derived", action="store_true")
    args = ap.parse_args(argv)
    conn = connect()
    try:
        if args.rebuild_derived:
            print("rebuilt:", rebuild_derived(conn) or "nothing needed")
        if args.maintain or args.vacuum:
            print(maintain(conn, vacuum=True if args.vacuum else None))
        if not (args.maintain or args.vacuum or args.rebuild_derived):
            ap.print_help()
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
